name : hello world workflow

on:
    push:
        branches:

            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with: 
                node-version: '20'

            - run: npm install
            - run: npm run wdio

            - name: Upload test report
              uses: actions/upload-artifact@v4.6.0
              if: always()
              with:
               name: test-report
               path: .result/report/index.html
